[Spike] Add `evm` contents
futureversecom/trn-docs pull request #12
Opened 2023-08-01 08:05 UTC by ken-centrality

## Summary

Lots of files changes due to code formatting, what to focus on reviewing is the content in

- Introduction
- Native JavaScript API / Cookbook / Asset
- EVM JavaScript API / Getting Started
- EVM JavaScript API / Cookbook / Asset

## Checklist

- [x] Add description
- [ ] Tag related issue(s)

2023-08-01 08:07 UTC, ken-centrality commented
@JasonTulp @zees-dev if you don't mind please review the accuracy of the content in those pages 🙏 

- Native JavaScript API / Cookbook / Asset
- EVM JavaScript API / Getting Started
- EVM JavaScript API / Cookbook / Asset

2023-08-01 20:43 UTC, aidan-starke requested changes
Looks good, couple grammar nits

2023-08-01 20:43 UTC, aidan-starke commented on docs/evm/getting-started.md
> +Similarly, the following will transfers `0.00001 $XRP` to `receiver`
```suggestion
Similarly, the following will transfer `0.00001 $XRP` to `receiver`
```

2023-08-01 20:43 UTC, aidan-starke commented on docs/evm/getting-started.md
> +or transfers `1.2 $XRP` to `receiver`
```suggestion
or transfer `1.2 $XRP` to `receiver`
```

2023-08-01 22:14 UTC, zees-dev reviewed
Looks good, couple more grammer nits

2023-08-01 22:14 UTC, zees-dev commented on docs/evm/getting-started.md
> +TRN uses a precompile system to allow communication between the TRN runtime and EVM contracts. This allows native TRN currencies and NFTs to appear as regular ERC20s and ERC721s to Ethereum tooling a
```suggestion
TRN exposes functionalities of certain pallets as precompiles, which allows users/tooling to query/transact with the pallet functions as if they are solidity functions. This also allows native TRN currencies and NFTs to appear as regular ERC20s and ERC721s to Ethereum tooling and contracts along side with other functionality to supercharge contract development such as as Decentralised Exchange (DEX), FuturePass, ERC1155.
```

2023-08-02 01:36 UTC, JasonTulp requested changes
Looks good overall, noted a few changes that could make the input parameters for NFT part a little clearer

2023-08-02 01:36 UTC, JasonTulp commented on docs/native/cookbook/asset.md
> +The `royaltiesSchedule` is in permil scaling, so if you want a 10% royalty, that would be `100000` (as `100_000 / 1_000_000 = 0.1`);
```suggestion
The `royaltiesSchedule` is in permill scaling, so if you want a 10% royalty, that would be `100,000` (as `100_000 / 1_000_000 = 0.1`);
```

2023-08-02 01:36 UTC, JasonTulp commented on docs/native/cookbook/asset.md
> +Once your collection is created, you can call the `nft.mint()` method on the collection contract to start minting
```suggestion
Once your collection is created, the collection owner can call the `nft.mint()` method on the collection contract to start minting additional tokens so long as the max issuance has not been reached
```

2023-08-02 01:36 UTC, JasonTulp commented on docs/native/cookbook/asset.md
> +- `collectionId` - The collection id
```suggestion
- `collectionId` - The unique collection id assigned when the collection was created
```

2023-08-02 01:36 UTC, JasonTulp commented on docs/native/cookbook/asset.md
> +- `crossChainCompatibility` - The cross-chain compatibility flag
```suggestion
- `tokenOwner` - The receiver of the tokens minted now, defaults to the caller
- `metadataScheme` - The off-chain metadata referencing scheme for tokens in this collection
- `royaltiesSchedule` - The defacto royalties plan for secondary sales, this will apply to all tokens in the collection
- `crossChainCompatibility` - The cross-chain compatibility flag allows for limited compatibility with XRPL at the cost of higher mint fees
```

2023-08-02 01:36 UTC, JasonTulp commented on docs/native/cookbook/asset.md
> +## How do I create and mint NFT on TRN?
```suggestion
## How do I create and mint an NFT on TRN?
```

2023-08-02 04:58 UTC, ken-centrality commented
ready for round 2, thanks for all the feedbacks team

2023-08-03 01:30 UTC, JasonTulp approved these changes
lgtm!

2023-08-03 08:51 UTC, merged